- name: install RPM-GPG-KEY-CentOS-6
  rpm_key:
    state: present
    key: http://mirror.centos.org/centos/6/os/x86_64/RPM-GPG-KEY-CentOS-6
  become: true

- name: Temporarily remove Duo repo
  file:
    state: absent
    path: "/etc/yum.repos.d/duosecurity.repo"
  become: true

- name: Force install the CentOS RPMs we downloaded
  shell: rpm -Uvh --force *.rpm
  args:
    chdir: /temp/centos/
  ignore_errors: True
  become: true

- name: Clean up yum one more time and then upgrade
  shell: yum clean all
  become: true

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    enabled: yes
    gpgcheck: no
  become: true

- name:  Update cache
  yum:
    update_cache: yes
  become: true

#- name: Install EPEL Release
#  yum:
#    name: epel-release
#    state: latest
#  become: true

#- name: update all packages
#  yum:
#    name: '*'
#    state: latest
#    exclude: kernel*,network*
#  become: true

- name: (PKG) Install standard system packges
  package:
    name: ['postfix', 'pexpect', 'yum-utils', 'rsyslog','samba-common', 'ntpdate', 'chrony', 'htop', 'net-snmp', 'net-snmp-utils']
    state: present
  become: true

- name: (PKG) Install python specific packges
  package:
    name: ['python-pip', 'policycoreutils-python', 'python-pycurl', 'python-setuptools', 'python-pycurl',]
    state: present
  become: true

- name:  Update BUGFIXES
  yum:
    bugfix: yes
    state: latest
    update_cache: yes
  become: true

- name:  Update SECURITY
  yum:
    security: yes
    state: latest
    update_cache: yes
  become: true
