- name: Remove RHN packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - rhnlib
    - abrt-plugin-bugzilla
    - redhat-release-notes*
    - redhat-release-server-6Server
    - redhat-indexhtml
  become: true

#- debug:
#    msg: "If the ‘rpm -e’ command fails saying one of the packages is not installed remove the package from the command and run it again."

#- name: Remove redhat-indexhtml
#  shell: rpm -e --nodeps redhat-release-server-6Server redhat-indexhtml
#  ignore_errors: True

#- debug:
#    msg: "If you do not do this every time you run ‘yum’ you will receive the following message: “This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register."

#- name: Remove left over RHEL subscription
#  shell: subscription-manager clean

- name: remove RHN Subscription Manager
  yum:
    name: subscription-manager
    state: absent
  become: true
