- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: upgrade all packages, excluding kernel & foo related packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*,foo*
  become: true

- name: print to stdout
  command: "uname -a "
  register: sysname
- debug: msg="{{ sysname.stdout }}"
