- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - import_tasks: "1_yum_prep.yml"
    - import_tasks: "2_mirror-match.yml"
    - import_tasks: "3_rhel-strip.yml"
    - import_tasks: "4_packages.yml"
    - import_tasks: "5_yum-upgrade.yml"
